[package]
name = "notes"
version = "0.1.0"
authors = ["Marten <me@marten.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.8.0"
regex = "1"
shellexpand = "2.1.0"
